Made the build workflow same date pre-release handling more robust.

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -150,18 +150,21 @@ jobs:
 
       - name: Delete same tag pre-release if exist.
         run: |
-          # Status values:
-          #   "false" - exists and is a release exists
-          #   "true"  - exists and is a pre-release
-          #   ""      - doesn't exist
-          status=$(gh release view "$RELEASE_TAG" --json isPrerelease -q .isPrerelease  || true)
-          echo "Status is [$status]"
-          if [[ "$status" == "false" ]]; then
+          set -e
+          gh release list --limit 100
+          output=$(gh release view "$RELEASE_TAG" --json name,tagName,isDraft,isImmutable,isPrerelease 2>&1 || true)
+          echo $output
+          if [[ "$output" == "release not found" ]]; then
+            echo "Release $RELEASE_TAG does not exist, safe to continue."
+          elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "true" ]]; then
+            echo "Release $RELEASE_TAG exists and is a pre-release, deleting."
+            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
+          elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "false" ]]; then
             echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
             exit 1
-          elif [[ "$status" == "true" ]]; then
-            echo "Deleting existing pre-release and tag $RELEASE_TAG."
-            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
+          else
+            echo "Error determining if release $RELEASE_TAG exists"
+            exit 1
           fi
         env:
           GITHUB_TOKEN: ${{ github.token }}
